name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  DOCKERHUB_SLUG: thesnallygaster/thruk-docker

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta (ubuntu)
        id: meta-ubuntu
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: |
            type=match,pattern=(.*),group=1
            type=match,pattern=(.*)-.*,group=1
            type=ref,event=pr
            type=edge
          labels: |
            org.opencontainers.image.title=thruk-docker
            org.opencontainers.image.description=Dockerized installation of thruk
            org.opencontainers.image.vendor=thesnallygaster
      -
        name: Docker meta (alpine)
        id: meta-alpine
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: |
            type=match,pattern=(.*),group=1
            type=match,pattern=(.*)-.*,group=1
            type=ref,event=pr
            type=edge
            type=raw,value=alpine,suffix=
          flavor: |
            latest=false
            suffix=-alpine,onlatest=false
          labels: |
            org.opencontainers.image.title=thruk-docker
            org.opencontainers.image.description=Dockerized installation of thruk
            org.opencontainers.image.vendor=thesnallygaster
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build (ubuntu)
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-ubuntu.outputs.bake-file }}
          targets: image-all
          push: ${{ github.event_name != 'pull_request' }}
      -
        name: Build (alpine)
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-alpine.outputs.bake-file }}
          targets: image-all-alpine
          push: ${{ github.event_name != 'pull_request' }}
      -
        name: Check manifest (ubuntu)
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
      -
        name: Check manifest (alpine)
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
      -
        name: Inspect (ubuntu)
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
          docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-ubuntu.outputs.version }}
      -
        name: Inspect (alpine)
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
          docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta-alpine.outputs.version }}
